Ruby on Rails/Blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
 devise_for :users
 resources :posts
 resources :projects
 resources :contacts, only: [:new, :create]
 get 'welcome/index'
 root 'welcome#index'
 #get '*path' => redirect('/')

namespace :admin do

  root  'base#index'

  delete '/admin/projects/:id' => 'admin/projects#destroy'
  
  resources :posts, only: [:create, :index, :update, :destroy, :edit, :show]
  resources :projects, only: [:create, :index, :update, :destroy, :edit, :show]
end

end

Ruby on Rails/Blog/app/models/admin.rb
class Admin < ApplicationRecord
  has_many :projects
  has_many :posts
  has_many :users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable
end

Ruby on Rails/Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby on Rails/Blog/app/models/assests.rb
# config/initializers/assets.rb

# ...

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile += %w( admin.js admin.css )

Ruby on Rails/Blog/app/models/contact.rb
class Contact < MailForm::Base

attribute :name,     :validate => true
  attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w]{2,})\z/i
  attribute :message,     :attachment => true
attribute :nickname, :captcha => true

def headers
 {
  :subject => "Contact Form",
  :to => "pro@test.com",
  :from => %("#{name}" <#{email}>)
 }
end

end

Ruby on Rails/Blog/app/models/post.rb
class Post < ApplicationRecord

 #validates_presence_of :title, :content

  validates :title, presence: true
  validates :title, length: {maximum: 100}


  def self.no_content     
            where(:content => nil)
  end

  def abstract
      self.content[0..20]
  end


end

Ruby on Rails/Blog/app/models/project.rb
class Project < ApplicationRecord

validates :title, presence: true

end

Ruby on Rails/Blog/app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :projects

  validates :email, presence: true
  validates :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

Ruby on Rails/Blog/app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
before_action :authenticate_admin!
layout 'admin'

def index
  @posts = Post.all 
  @projects = Project.all
end

def show
  @posts = Post.find(params[:id])
  @projects = Project.find(params[:id])
end


end

Ruby on Rails/Blog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  
  def index

    @posts = Post.all 

  end

  def new 
  
  @post = Post.new

  end

  def create
  
  @post = Post.new(post_params)
  if @post.save
     redirect_to admin_posts_path, notice: "Post was created sucessfully!"
    else
      render 'admin/posts/new'
    end

  end

  def edit
  
  @post = Post.find(params[:id])

  end


  def update
    @post = Post.find(params[:id])
    if @post.update post_params
      redirect_to admin_posts_path, notice: "The article was sucessfully"
    else
      render 'edit'
    end
  end

   def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

 


  protected 

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

Ruby on Rails/Blog/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController



def index

    @projects = Project.all 

  end

  def new 
  
  @project = Project.new

  end

  def create
  
  @project = Project.new(project_params)
  if @project.save
     redirect_to admin_project_path, notice: "Project was created sucessfully!"
    else
      render 'admin/projects/new'
    end

  end

   def edit
  
  @project = Project.find(params[:id])

  end


  def update
    @project = Project.find(params[:id])
    if @project.update project_params
      redirect_to admin_projects_path, notice: "The article was sucessfully"
    else
      render 'edit'
    end
  end

   def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path
  end

  def show
    @project = Project.find(params[:id])
  end



  protected 

  def project_params
    params.require(:project).permit(:title, :description, :link)
  end

end

Ruby on Rails/Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Ruby on Rails/Blog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
  @contact = Contact.new
end

def create
  @contact = Contact.new(params[:contact])
  @contact.request = request
  if @contact.deliver
    flash.now[:error] = nil
  else
    flash.now[:error] = 'Cannot send message.'
    render :new
  end
end



end

Ruby on Rails/Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("created_at desc").paginate(page: params[:page], per_page: 2)
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: "Post is created sucessfully!"

    else
      render 'new', notice: "It's unable to be saved"
    end
  end

  def show
    post
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    if post.update post_params
      redirect_to @post, notice: "The article was sucessfully"
    else
      render 'edit'
    end
  end

  def destroy
    post.destroy
    redirect_to posts_path
  end

  

protected 

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def post
    @post ||= current_user.posts.find(params[:id])
  end
end

Ruby on Rails/Blog/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
 
  def index
    @projects = current_user.projects.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    @project.user = current_user
    if @project.save
      redirect_to @project, notice: "Project was created sucessfully!"
    else
      render 'new'
    end
  end

  def show
    project
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    if project.update project_params
      redirect_to @project, notice: "Project has been updated and saved!"
    else
      render 'edit'
    end

  end

  def destroy
    project.destroy
    redirect_to projects_path
  end

  

  private

  def project
    @project ||= current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link)
  end

end

Ruby on Rails/Blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.limit(3).order("created_at desc")
    @projects = current_user.projects.limit(3).order("created_at desc")
  end


end

Ruby on Rails/Blog/app/helpers/application_helper.rb
module ApplicationHelper
  
end

Ruby on Rails/Blog/app/helpers/contacts_helper.rb
module ContactsHelper
end

Ruby on Rails/Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Ruby on Rails/Blog/app/helpers/projects_helper.rb
module ProjectsHelper
end

Ruby on Rails/Blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Ruby on Rails/Blog/app/views/admin/base/index.html.erb
    <div class="wrapper wrapper_padding clearfix">
      <div class="col-1 about homepage_content">
        <h2>About</h2>
        <hr>
        <p>Here you can find more info. about <a href="#">us</a></p>
      </div>

      <div class="col-2 homepage_content">
        <h2>Stuff I'v Writtne</h2>
        <hr>
        <% @posts.each do |post| %>
        <h3><a href="#"><%= link_to post.title, admin_posts_path %></a></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
        <% end %>
        
      </div>
      
      <div class="col-3 homepage_content">
        <h2>Stuff I'v Built</h2>
        <hr>
        <% @projects.each do |project| %>
        <h3><a href="#"><%= link_to project.title, admin_projects_path %></a></h3>
        <p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>
        <% end %>
        
      </div>
    </div>
    

Ruby on Rails/Blog/app/views/admin/posts/_form.html.erb
<%= form_for @post, url: admin_post_path(@post), method: :put do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "You can write your article here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

Ruby on Rails/Blog/app/views/admin/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>
<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

Ruby on Rails/Blog/app/views/admin/posts/index.html.erb
<h1 id="page_title">Stuff I written</h1>
    <div id="posts_wrapper" class="skinny_wrapper">

      <% @posts.each do |post| %>
      
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B, %d') %></p>
        <h2><a href="#"><%= link_to post.title, admin_post_path(post) %></a></h2>
          <hr>
        </div>
        <% end %>
        
       </div>

      
       

Ruby on Rails/Blog/app/views/admin/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @post.created_at.strftime('%A, %B, %d') %></p>
        <h1><%= @post.title %></h1>
        <hr>
        <p>by <%= link_to @post.user %></p>
      </header>

      <div id="content">
        <%= @post.content %>
        
      </div>
      <br>

      
       
      <div id="admin_links">
        <%= link_to "Edit Article", edit_admin_post_path(@post) %>
        <%= link_to "Delete Article", admin_post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>

      </div>
      
      
      <hr>

      <div id="share_box">
        <p>Share To DO list</p>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-google-plus"></i></a>
      </div>

      <hr>

    </div>

Ruby on Rails/Blog/app/views/admin/projects/_form.html.erb
<%= form_for @project, url: admin_project_path(@project), method: :put do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
<ul>
  <% @project.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :description%><br>
<%= f.text_area :description %>

<br>
<br>


<%= f.label :link %><br>
<%= f.text_field :link %>

<br>
<br>

<%= f.submit %>

<% end %>

Ruby on Rails/Blog/app/views/admin/projects/edit.html.erb
<h1 id="page_title">Edit Post</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form'%>
</div>

Ruby on Rails/Blog/app/views/admin/projects/index.html.erb
<h1 id="page_title">Stuff I Built</h1>
    <div id="posts_wrapper" class="skinny_wrapper">

      <% @projects.each do |project| %>
      
      <div class="project">
        <p class="date"><%= project.created_at.strftime('%A, %B, %d') %></p>
        <h2><a href="#"><%= link_to project.title,admin_project_path(project)%></a></h2>
          <hr>
        </div>
        <% end %>
        
       </div>
       
       

Ruby on Rails/Blog/app/views/admin/projects/show.html.erb
<div id="project_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @project.created_at.strftime('%A, %B, %d') %></p>
        <h1><%= @project.title %></h1>
        <hr>
        <p>by <%= link_to @project.user %></p>
      </header>

      <div id="content">
        <%= @project.description %>

        <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
        
      </div>
    </div>

    <% if admin_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_admin_project_path(@project)%>
      <%= link_to "Delete", admin_project_path(@project), method: :delete, data: {confirm: "Are you sure?"}%>
      </div>
      <% end %>

      <hr>
    </div>

Ruby on Rails/Blog/app/views/contacts/create.html.erb
<h1 id="page_title">Hello</h1>

<div class="skinny_wrapper wrapper_padding">

<h1>Thank you for your message!</h1>
<p>I'll get you back soon</p>

</div>

Ruby on Rails/Blog/app/views/contacts/new.html.erb
<h1 id="page_title">Hello</h1>
      <div class="skinny_wrapper wrapper_padding">

        <%= form_for @contact do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name, required: true %>

        <br>

        <%= f.label :email %><br>
        <%= f.email_field :email, required: true %>
          
          <br>


        <%= f.label :message %><br>
        <%= f.text_area :message, as: :text %>

        <div class="hidden">
          <%= f.label :nickname %><br>
          <%= f.text_field :nickname, hint: 'leave this field blank' %>
        </div>

        <%= f.submit 'Send Message', class: "button"%>

        <% end %>

        
      </div>

Ruby on Rails/Blog/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="stylesheet/admin">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'base', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'base', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header id="main_navigation" class="clearfix">

      <%= link_to "Blogs", root_path, class: "name" %>
      <nav>
        <% if admin_signed_in? %>
        <h4>Admin</h4>
        <%= link_to "Articles", admin_posts_path %>
        <%= link_to "Projects", admin_projects_path %>
       <%= link_to "Contact", new_contact_path %>
       <%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
       <% else %>
       <%= link_to 'Login', new_admin_session_path %>
       <% end %>
       
      </nav>


    </header>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% elsif alert %>
    <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

     <footer id="main_footer">
      <p class="copyright">&copy;2019 HundrED</p>
      <nav>
        <a href="http://twitter.com" target="blank"><i class="fab fa-twitter"></i></a>
        <a href="http://facebook.com" target="blank"><i class="fab fa-facebook-f"></i></a>
        <a href="https://hundred.org/en" target="blank"><i class="fas fa-globe"></i></a>
      </nav>
    </footer>
  </body>
</html>

Ruby on Rails/Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="stylesheet/application">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="main_navigation" class="clearfix">

      <%= link_to "Blogs", root_path, class: "name" %>
      <nav>
        
        <%= link_to "Articles", posts_path %>
        <%= link_to "Projects", projects_path %>
       <%= link_to "Contact", new_contact_path %>
      
       <% if user_signed_in?%>
       <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
       <% else %>
       <%= link_to 'Login', new_user_session_path %>
       <% end %>
      </nav>
    </header>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% elsif alert %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

     <footer id="main_footer">
      <p class="copyright">&copy;2019 HundrED</p>
      <nav>
        <a href="http://twitter.com" target="blank"><i class="fab fa-twitter"></i></a>
        <a href="http://facebook.com" target="blank"><i class="fab fa-facebook-f"></i></a>
        <a href="https://hundred.org/en" target="blank"><i class="fas fa-globe"></i></a>
      </nav>
    </footer>
  </body>
</html>

Ruby on Rails/Blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "You can write your article here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

Ruby on Rails/Blog/app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>
<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

Ruby on Rails/Blog/app/views/posts/index.html.erb
<h1 id="page_title">Stuff I written</h1>
    <div id="posts_wrapper" class="skinny_wrapper">

      <% @posts.each do |post| %>
      
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B, %d') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
          <hr>
        </div>
        <% end %>
        
       </div>
       
       <%= will_paginate @posts %>

Ruby on Rails/Blog/app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>
<div class="skinny_wrapper wrapper_padding">
  
  <%= render 'form'%>
</div>

Ruby on Rails/Blog/app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @post.created_at.strftime('%A, %B, %d') %></p>
        <h1><%= @post.title %></h1>
        <hr>
        <p>by <%= link_to @post.user %></p>
      </header>

      <div id="content">
        <%= @post.content %>
        
      </div>
      <br>

      <% if @post.user == current_user %>
      <div id="admin_links">
        <%= link_to "Edit Article", edit_post_path(@post) %>
        <%= link_to "Delete Article", post_path(@post), method: :delete, data: {confirm: "Are you sure?" } %>
      </div>
      <% end %>

      <hr>

      <div id="share_box">
        <p>Share To DO list</p>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-google-plus"></i></a>
      </div>

      <hr>

    </div>




<br>
<br>

Ruby on Rails/Blog/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
<ul>
  <% @project.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :description%><br>
<%= f.text_area :description %>

<br>
<br>


<%= f.label :link %><br>
<%= f.text_field :link %>

<br>
<br>

<%= f.submit %>

<% end %>

Ruby on Rails/Blog/app/views/projects/edit.html.erb
<h1 id="page_title">Edit Post</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form'%>
</div>

Ruby on Rails/Blog/app/views/projects/index.html.erb
<h1 id="page_title">Stuff I Built</h1>
    
    <div id="posts_wrapper" class="skinny_wrapper">

      <% @projects.each do |project| %>
      
      <div class="project">
        <p class="date"><%= project.created_at.strftime('%A, %B, %d') %></p>
        <h2><a href="#"><%= link_to project.title, project %></a></h2>
          <hr>
        </div>
        <% end %>
        
       </div>
       

Ruby on Rails/Blog/app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>
<div class="skinny_wrapper wrapper_padding">
  
  <%= render 'form'%>
</div>

Ruby on Rails/Blog/app/views/projects/show.html.erb
<div id="project_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @project.created_at.strftime('%A, %B, %d') %></p>
        <h1><%= @project.title %></h1>
        <hr>
        <p>by <%= link_to @project.user %></p>
      </header>

      <div id="content">
        <%= @project.description %>

        <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
        
      </div>
    </div>

    <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_project_path(@project)%>
      <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}%>
      </div>
      <% end %>

      <hr>
    </div>

Ruby on Rails/Blog/app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
      <div class="col-1 about homepage_content">
        <h2>About</h2>
        <hr>
        <p>Here you can find more info. about <a href="#">us</a></p>
      </div>

      <div class="col-2 homepage_content">
        <h2>Stuff I'v Writtne</h2>
        <hr>
        <% @posts.each do |post| %>
        <h3><a href="#"><%= link_to post.title, post %></a></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
        <% end %>
        
      </div>
      
      <div class="col-3 homepage_content">
        <h2>Stuff I'v Built</h2>
        <hr>
        <% @projects.each do |project| %>
        <h3><a href="#"><%= link_to project.title, project %></a></h3>
        <p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>
        <% end %>
        
      </div>
    </div>

   